name: Detect breaking changes in schema
on: pull_request
# Add github token in repository settings
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.1]
    
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GraphQL-Inspector
        run: yarn global add @graphql-inspector/cli

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'yarn'

      - name: Get base branch of PR
        id: getBasePR
        run: echo ::set-output name=baseSHA::${{ github.event.pull_request.base.sha }}

      - name: Install Graphql
        run: yarn global add graphql --ignore-engines

      - name: Run yarn
        run: yarn

      - name: Run schema diff
        id: graphqldiff
        run: graphql-inspector diff 'git:${{steps.getBasePR.outputs.baseSHA}}:./src/schemas/**/*.graphql' src/schemas/**/*.graphql

      - name: Add label to PR
        if: steps.graphqldiff.outcome == 'failure' && always()
        uses: buildsville/add-remove-label@v1
        with: 
          token: ${{secrets.GITHUB_TOKEN}}
          label: breaking-schema-change
          type: add
      
      - name: Remove label if it exists
        if: steps.graphqldiff.outcome == 'success'
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: breaking-schema-change
          type: remove